[package]
name = "channels-packet"
version = "0.1.0"
edition = "2021"
authors = ["1337"]
license = "MIT"
repository = "https://github.com/threadexio/channels-rs"
description = """
Utilities to parse channels packets.
"""
categories = ["parsing", "parser-implementations", "no-std"]
keywords = ["paser", "binary", "packet"]
readme = "README.md"

[dependencies]
