[workspace]
members = [
	"channels",
	"channels-packet",
	"channels-serdes",
	"channels-io",
	"channels-macros",
	"benches",
	"stress-tests",
	"tests-integration",
	"examples",
	"examples/chat-app",
]
resolver = "2"

[workspace.dependencies]
channels = { path = "./channels", features = ["full"] }
