[workspace]
resolver = "2"
members = [
	"channels",
	"channels-packet",
	"channels-serdes",
	#"tests-integration",
	#"stress-tests",
	#"examples",
	#"examples/chat-app",
]

[workspace.dependencies]
channels = { path = "./channels", features = ["full"] }
