[workspace]
resolver = "2"
members = [
	"channels",
	"channels-packet",
	"channels-serdes",
	"examples",
	"tests-integration",
	"stress-tests",
]

[workspace.dependencies]
channels = { path = "./channels", features = ["full"] }
