[package]
name = "channels"
description = "Bidirectional channel-like communication over generic Read/Write streams"
version = "0.6.2"
edition = "2021"
authors = ["1337"]
license = "MIT"
repository = "https://github.com/threadexio/channels-rs"
documentation = "https://docs.rs/channels"
readme = "README.md"
keywords = ["client", "networking", "server", "stream", "channel"]
categories = ["network-programming"]

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
crc = "3.0"

[dev-dependencies]
rand = "0.8"

[features]
statistics = []
