[package]
name = "channels"
description = "Bidirectional channel-like communication over generic Read/Write streams"
version = "0.2.0"
edition = "2021"
authors = ["1337"]
license = "MIT"
repository = "https://github.com/threadexio/channels-rs"
documentation = "https://docs.rs/channels"
readme = "README.md"
keywords = ["client", "networking", "server", "stream", "channel"]
categories = ["network-programming"]

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
bincode = "^1"

crc = { version = "^3", optional = true }
crypto = { version = "^0.4", optional = true }

[features]
crc8 = ["dep:crc"]
crc16 = ["dep:crc"]
crc32 = ["dep:crc"]
crc64 = ["dep:crc"]
