[package]
name = "channels"
description = "Bidirectional channel-like communication over generic Read/Write streams"
version = "0.6.4"
edition = "2021"
authors = ["1337"]
license = "MIT"
repository = "https://github.com/threadexio/channels-rs"
documentation = "https://docs.rs/channels"
readme = "README.md"
keywords = ["client", "networking", "server", "stream", "channel"]
categories = ["network-programming"]

include = ["/src", "/examples", "LICENSE"]

[dependencies]
thiserror = "1.0"
crc = "3.0"

serde = { version = "1.0", optional = true }
bincode = { version = "1.3", optional = true }

[dev-dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }

[features]
default = ["serde"]

statistics = []
serde = ["dep:serde", "dep:bincode"]
