[package]
name = "channels-serdes"
version = "0.1.0"
edition = "2021"
authors = ["1337"]
license = "MIT"
repository = "https://github.com/threadexio/channels-rs"
description = """
Utilities to serialize/deserialize types.
"""
categories = ["parsing", "parser-implementations"]

[features]
bincode = ["dep:serde", "dep:bincode"]
cbor = ["dep:serde", "dep:ciborium"]
json = ["dep:serde", "dep:serde_json"]

[dependencies]
channels-packet = { version = "0.1.0", path = "../channels-packet" }

cfg-if = "1.0"

bincode = { version = "1.3", optional = true }
ciborium = { version = "0.2", optional = true }

[dependencies.serde]
version = "1.0"
default-features = false
optional = true

[dependencies.serde_json]
version = "1.0"
default-features = false
features = ["alloc"]
optional = true
