[package]
name = "channels"
description = "Bidirectional channel-like communication over generic Read/Write streams"
version = "0.9.2"
edition = "2021"
authors = ["1337"]
license = "MIT"
repository = "https://github.com/threadexio/channels-rs"
documentation = "https://docs.rs/channels"
readme = "README.md"
keywords = ["client", "networking", "server", "stream", "channel"]
categories = ["network-programming"]

include = ["/src", "LICENSE"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bincode = { version = "1.3", optional = true }
ciborium = { version = "0.2", optional = true }
crc = { version = "3.0", optional = true }
flate2 = { version = "1.0", optional = true }
hmac = { version = "0.12", optional = true }
sha3 = { version = "0.10", optional = true }
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
tokio = { version = "1.29", features = ["io-util", "rt"], optional = true }

[features]
default = ["serde", "bincode"]
full = [
	"statistics",
	"serde",
	"bincode",
	"cbor",
	"crc",
	"flate2",
	"hmac",
	"json",
	"tokio",
]

bincode = ["dep:bincode"]
cbor = ["dep:ciborium"]
crc = ["dep:crc"]
flate2 = ["dep:flate2"]
hmac = ["dep:hmac", "dep:sha3"]
json = ["dep:serde_json"]
serde = ["dep:serde"]
statistics = []
tokio = ["dep:tokio"]
