[package]
name = "channels"
description = "Bidirectional channel-like communication over generic Read/Write streams"
version = "0.10.0"
edition = "2021"
authors = ["1337"]
license = "MIT"
repository = "https://github.com/threadexio/channels-rs"
documentation = "https://docs.rs/channels"
readme = "README.md"
keywords = ["client", "networking", "server", "stream", "channel"]
categories = ["no-std", "network-programming"]

[dependencies]
channels-packet = { version = "0.1.0", path = "../channels-packet" }
channels-io = { version = "0.1.0", path = "../channels-io" }
channels-serdes = { version = "0.1.0", path = "../channels-serdes" }

serde = { version = "1.0", default-features = false, optional = true }
tokio = { version = "1", features = ["net"], optional = true }
futures = { version = "*", optional = true }

[features]
default = ["std", "bincode"]
full = ["std", "statistics", "bincode", "cbor", "json"]

std = ["channels-io/std"]
statistics = []

futures = ["channels-io/futures", "dep:futures"]
tokio = ["channels-io/tokio", "dep:tokio"]

bincode = ["channels-serdes/bincode", "dep:serde"]
cbor = ["channels-serdes/cbor"]
json = ["channels-serdes/json"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
