[package]
name = "tests-integration"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
channels = { workspace = true }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
