name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check --all
      - run: cargo check --workspace
      - run: cargo clippy --all

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
    runs-on: ${{ matrix.os }}-latest
    name: Test on ${{ matrix.os }}-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --workspace --features full,tokio

  doc:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
      - uses: dtolnay/install@cargo-docs-rs
      - run: cargo +nightly docs-rs -p channels
      - run: cargo +nightly docs-rs -p channels-serdes
      - run: cargo +nightly docs-rs -p channels-packet

  miri:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@miri
      - run: cargo +nightly miri setup
      - run: cargo +nightly miri test --all-features -p channels-packet
