name: CI

on:
  push:
  pull_request:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTFLAGS: -D warnings

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check --all
      - run: cargo clippy --workspace --all-features

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Test on ${{ matrix.os }}
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --workspace --all-features --no-run
      - run: cargo test --workspace --all-features -- --nocapture --quiet

  doc:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
      - run: cargo +nightly doc --workspace --no-deps --all-features

  miri:
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-gnu, s390x-unknown-linux-gnu]
    runs-on: ubuntu-latest
    name: miri (${{ matrix.target }})
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@miri
        with:
          targets: ${{ matrix.target }}

      - run: cargo +nightly miri setup
      - run: cargo +nightly miri test --target ${{ matrix.target }} --all-features -p channels-io -p channels-packet -p channels-serdes -p channels --lib
