name: Docs

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings --cfg channels_nightly
      RUSTDOCFLAGS: --cfg channels_nightly
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
      - run: cargo +nightly doc --all-features --no-deps

      - name: Prepare target/doc/
        run: |
          set -eu
          rm -f target/doc/.lock
          echo '<meta http-equiv="refresh" content="0;url=channels/index.html">' > target/doc/index.html

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build-docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
