name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[no-ci]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Format
        run: |
          cargo fmt --check

      - name: Test
        run: |
          cargo test --all-features -j$(nproc) -- --test-threads=$(nproc)
